FROM python:3.12-slim

WORKDIR /app

COPY ./streamlit /app

RUN pip install --no-cache-dir streamlit pandas extra-streamlit-components joblib

EXPOSE 8888

CMD ["streamlit", "run", "streamlit.py", "--server.port=8888"]
